version: '3'
services:
  opentiku-web-app:
    image: "jyffe/opentiku-web-app"
    ports:
     - "8080:8080"
  opentiku-event-service:
    image: "jyffe/opentiku-event-service"
    depends_on:
    - "kafka"
    ports:
     - "8088:8088"
  opentiku-firealarm-integration:
    image: "jyffe/opentiku-firealarm-integration-service"
  kafka:
    image: "spotify/kafka"
    ports:
    - "2181:2181"
    - "9092:9092"
    environment:
    - ADVERTISED_HOST=kafka
    - ADVERTISED_PORT=9092