version: '3'
services:
  sa-poc-web-app:
    image: "jyffe/sa-poc-web-app"
    ports:
     - "8080:8080"
  sa-poc-chat-service:
    image: "jyffe/sa-poc-chat-service"
    ports:
     - "8090:8090"
  sa-poc-event-service:
    image: "jyffe/sa-poc-event-service"
    ports:
     - "8088:8088"
  