version: '3'
services:
  opentiku-web-app:
    image: "jyffe/opentiku-web-app"
    ports:
     - "8080:8080"
  opentiku-event-service:
    image: "jyffe/opentiku-event-service"
    depends_on:
    - "kafka"
    ports:
     - "8088:8088"
  opentiku-firealarm-integration:
    image: "jyffe/opentiku-firealarm-integration-service"
  # Kafka event.t partitioning needs to be revised before enabling this service, otherwise the topic is owned in random by 
  # firealarm-integration-service or bu target-service!
  #opentiku-target-service:
    #image: "jyffe/opentiku-target-service"
    #depends_on:
    #- "kafka"
    #ports:
    #- "8100:8080"
  kafka:
    image: "spotify/kafka"
    ports:
    - "2181:2181"
    - "9092:9092"
    environment:
    - ADVERTISED_HOST=kafka
    - ADVERTISED_PORT=9092